CODE_REVIEW.md

These are the steps that will be followed by the U.S. Tax Court when reviewing each pull request.

Document the court's code review process

---

SETUP.md
document-service/Jenkinsfile
document-service/sonar-project.properties
document-service/verify-sonarqube-passed.sh
web-client/Jenkinsfile
web-client/sonar-project.properties
web-client/verify-sonarqube-passed.sh

Allowing the sonarqube key to be configurable

Allow Dynamic Sonarqube

---

SETUP.md
efcms-service/Jenkinsfile
efcms-service/sonar-project.properties
efcms-service/verify-sonarqube-passed.sh
web-client/Jenkinsfile
web-client/sonar-project.properties
web-client/verify-sonarqube-passed.sh

Adding support for configurable sonarcloud keys (updated SETUP.md to explain how to set those up in Jenkins as environment variables)

configurable sonar project keys

---

README.md
efcms-service/README.md
web-client/src/main/sequences.js

Addressing some PR comments, including
- update readme to have `npm run install:dynamodb`
- update readme to contain top level overview of how to run project in two terminals
- clearing the error alert if the user is successfully logged in

Addressing some PR comments

---

SETUP.md

It won't work in any other directory, because Terraform can't find the site data.

Specify directory in which to run Jenkins setup

---

Dockerfile.deploy
Dockerfile.web-client
efcms-service/docker-serverless.sh
efcms-service/package.json

- fixes the issue related to the serverless deploy package being too large... this was because we were including a lot of development dependencies in the zip.

Reduce API Deploy Zip Size

---

CODE_REVIEW.md

* Be more specific about what Chrome's audit tool can be called.
* Affix some comments to `README.md`

Update code review to reflect current practices

---

README.md

Copyediting changes, plus adding a technical overview.

Clean up, add technical overview to README

---

CODE_REVIEW.md

This will be a lot more useful in `staging` than in `master`.

Move over code review doc

---

README.md

Documentation is scattered around, but let's centralize links to it all.

Add a documentation section

---

docker-run.sh
wait-until.sh
web-client/package.json

- prints a build successful url if the ui hosts successfully
- fixes the bug where the wait will run forever if the build fails for some reason

Fix for the wait

---

CODE_REVIEW.md

As of sprint 8, the volume of code exceeds what can be reasonably reviewed. Also, test coverage is high. Solution: this.

Update code review process to reflect testing emphasis

---

CODE_REVIEW.md

This describes the process that I talked through with Flexion last week.

Add a security audit of dependencies, other minor changes

---

SETUP.md

Some changes must be made to set everything up properly, a result of changes and newly-discovered requirements.

Update the setup instructions to match reality

---

README.md

Flexion has put together user personas, as a living document in Figma. Flexion will capture any changes at the end of each sprint and update the PDF in GitHub. Here is the first commit of this document.

Add user personas PDF

---

README.md

* Excise a few mentions of Jenkins
* Standardize section-title case
* Document use of serverless-dynamodb-local
* Light copyediting throughout

Light copyediting, documenting extra dependency

---

.github/PULL_REQUEST_TEMPLATE/merge-to-master.md

Now that we've used this template a couple of times, it's clear that some elements are going to be present in every PR. This incorporates those elements.

Update template to reflect its use

---

docs/CODE_REVIEW.md
docs/SETUP.md

This PR includes changes to our setup instructions and to our code review instructions.
Most of the changes are copyediting and modifications for clarity, but there are also significant modifications to be more explicit about the new process for creating and managing permissions.
These changes don't modify the process at all, but instead are more specific and instructional. The exact commands are provided for cloning the pull request, and links are provided to Flexion's SonarCloud environment.

Clean up the documentation

---

README.md
web-api/README.md

- Link to Docker installation instructions
- Detail the necessary Docker resources
- Improve formatting of list of test accounts

Improve documentation around setup

---

docs/SETUP.md

There are some typos, inaccurate paths, filenames, and formatting.

Clean up setup script

---

.circleci/config.yml
Dockerfile
cypress-smoketests/integration/petitionsclerk-can-login.spec.js
web-api/setup-cognito-users.sh

A series of debug commits were made to `staging` in the past few days — this brings them forward to this branch.

Update branch from staging

---

docs/SETUP.md

Now that I'm using these instructions, I'm improving them.

Edits to new environment instructions

---

docs/SETUP.md

This could save folks a lot of frustration.

Describe need for larger Circle instances

---

docs/branch-management.md

It's not enough to update permissions for the PR to `staging` — we need that step for every branch.

Add IAM-update step to all environments

---

docs/TROUBLESHOOTING.md

- Add a new section about dealing with permissions problems
- Update the formatting a little

Update troubleshooting document

---

docs/how-we-work.md

This incorporates the "How We Work"  document into the `/docs/` directory.

Document how the Court conducts this project

---

README.md

Add a link to the new "How We Work" document, and also do a little textual cleanup.

Clean up README, link to "How We Work"

---

web-api/deploy-diff.sh

Apply patch from https://github.com/flexion/ef-cms/pull/4828/files

return correct value in order to trigger deploys

---

web-api/create-cognito-user.sh

This script can be run locally with the expected parameters and required permissions to create a user on any environment. 
These are the password requirements:

Fixes for create-cognito-user script

---

docs/SETUP.md

* Add a step that was missing
* Explain that two attempts may be required

Improve new environment documentation

---

web-api/create-cognito-user.sh

This confirms that the provided parameters exist and, in the case of the password, are conformant. This also ensures that JSON is returned, instead of relying on the user's account-level configuration.

Add parameter-checking, force JSON

---

docs/TROUBLESHOOTING.md

We got hung up for a couple of days on this error, so best to document it here, because it's bound to happen again.

Document stack-limit error and solution

---

web-api/terraform/bin/environment-destroy.sh
web-client/terraform/bin/environment-destroy.sh

Make sure that the necessary variables are set before proceeding.

Add variable verification to environment destruction

---

docs/TROUBLESHOOTING.md

This reverts commit 840cd304ea1255cca8aa810134ac31d7739bf87b. Doing this to resolve a merge conflict.

Fix problematic, conflicting commit

---

.circleci/config.yml
README.md
config/irs.yml
config/mig.yml
get-env.sh
get-es-instance-count.sh
get-keys.sh
web-api/config/irs.yml
web-api/config/mig.yml

This PR merges `test` into `staging` resolving merge conflicts. 
There are [64 commits that are on `test` that do not exist in staging](https://github.com/ustaxcourt/ef-cms/compare/9ac20fa937c940fecac3ec5d2e4517fba6690a21...test). Omitting the documentation-only commits leaves us with: 
- Add configuration for the `irs` environment: ec4e6aa13ea793e285e9b70d1e08198ba973c7c9, b1b56108041e03a229944e312807de020d5dc655, 30eba4e1fed44520bbd048bef56ddd528b49e7c8
- Add configuration for the `migration` environment: 665554fa0c3b1130f1a5f6be05bb5dd78da4b6d4, 30b5d257eb16f03f56c4387b6d5ad48cdf6e90f5, 793e2bc59065af8ab894868decafad2e43186300, 2ecb0318328f8f7ac6890d9e8fc83676416621ea, 49d83858ee3da398225202844779a03dbc48b5cd, fb154570a7849fc3f5e4b99535ba27fa14f6c461, …

Fix merge conflicts between staging and test.

---

.circleci/config.yml

This is a stop-gap until we have a better user strategy. Pending discussion in Slack.

Don’t deploy generic users in master (as well as migration).

---

get-env.sh
get-es-instance-count.sh
get-keys.sh

Adding experimental2 environment to fix conflicts found in #210 .

Add experimental2 env

---

README.md

This PR adds the additional backlogs and their descriptions as discussed this week.

Update backlog documentation.
