document-service/terraform/template/acm.tf
management/modules/management/jenkins.tf
web-client/terraform/common/frontend.tf

This module was previously pointing at the "master" branch of a third party module... this PR locks it down to version 0.1.2

pointing the third party acm module to a specific 0.1.2 version

---

SETUP.md

This is useful because Flexion uses `efcms` and U.S. Tax Court uses `ef-cms` (right now), so highlighting this step is really to stop me from getting confused.

Document how to set the AWS tag

---

CODE_REVIEW.md

The code review's imperative is rooted in the QASP (or the "Deliverables and Performance Standards" section of the SOW, in the case of this RFQ), so here we connect the dots between the code review and the QASP, as a reminder of the contractual basis of the code review work, and the standards that we must ensure that the work meets.

Incorporate the QASP

---

CODE_REVIEW.md

Sprint 7 incorporates Docker-based OWASP ZAP testing. Flexion is running it on their end to ensure that there are no errors. This could be gated as a part of the CD pipeline, but that would only work if there were _no_ errors and, in fact, there are several errors that we consider acceptable. We may modify this process down the line (e.g., configure OWASP ZAP to ignore those errors), but for now, the process is for them to run OWASP ZAP before filing an end-of-sprint PR and direct the output to `docs/`, which we then review to confirm that there are no errors that we have not previously said are acceptable (in the code review process, on a PR).

Document OWASP ZAP review process

---

CODE_REVIEW.md

The Court has committed to using Chrome internally, meaning that development can emphasize Chrome (though not to the detriment of other browsers), and eschew Internet Explorer 11. However, public-facing pages must function on the browsers that the public relies on, including IE 11.

Update testing process to reflect browser choices

---

README.md

Restructure the headers (they weren't nested correctly before) and spell out more clearly what the two different authentication mechanisms are.

Minor edits to make the Readme more clear

---

CODE_REVIEW.md

Every couple of sprints, there's a problem that has resulted from cached Docker assets. And every couple of sprints, I get 15 minutes into the code review before I realize that I haven't updated my local copy. This step will prevent these problems.

Start off code reviews with a blank slate

---

.github/ISSUE_TEMPLATE/merge-to-master.md
docs/merge-to-master.md

This adds a new template for GitHub issues, one that’s intended for proposing to move code from `staging` into `master`. It's a checklist of everything that needs to be provided in order to approve that pull request.
This would be better as a pull-request template, but GitHub doesn't support multiple pull-request templates like they do for issue templates, so we’ll start like this. Presumably GitHub will add that feature before we use this functionality many times.

Add a "merge to master" issue template

---

README.md

There are two changes here:
1. Fix the URL for the CircleCI badge that shows the build status — it has a typo in it.
2. There were a few parts of the instructions that I found confusing when I was following them, so I've modified them to make them more explicit.

Update CircleCI-related aspects of the README

---

README.md

I thought I'd fixed this in #63, but I missed a character. So here's a PR to delete exactly one character.

Fix typo in CircleCI badge URL

---

docs/CODE_REVIEW.md

At the recommendation of Flexion, start off each review by running the cleanup script. This is to avoid dependency errors.

Add cleanup step to review process

---

README.md

We moved the code review doc a sprint or two ago, but forgot to update this link to it.

Fix code review link

---

README.md

The style guide is stored in Figma, where it is not available publicly. It has a simple function to export the style guide as a PDF, which I did, and then added the style guide to the repository. I also added a link to it from the README. Flexion intends to update this with each sprint.

Add the visual style guide

---

efcms-service/package-lock.json
efcms-service/package.json

For reasons of dealing with an upstream security problem (with the tar npm module), an employee of the vendor needed to fork a project to patch it. Here we have forked _his_ fork, so that the Court is controlling its own copy of the code. This is likely to be a transient situation, until such time as the fix to this tar module flows downstream to us.
The relevant change here is a single line in `package.json`, where we've gone from including @sutt0n's package to including it from the U.S. Tax Court's GitHub organization. The `package-lock.json` change is just a lower-order realization of that modification.

Switch to using USTC's fork of a project

---

docs/README.md

After moving the documentation into `/docs/`, I didn't update the links to remove the `docs/` prefix, so the links are broken. This fixes those links so that they work again.

Fix /docs/ paths to linked files

---

README.md

Previously, it was necessary to specify that that `staging` holds all work, and `master` would show no activity. Now that we've merged work from `staging` to `master`, and intend to do so routinely, that's no longer the case. But now the absence of any badges for `master` is weird (there's no build status, etc.), so I've replaced the old disclaimer with a new disclaimer.

Work can now be found in staging and master

---

policy.json.tpl

Without giving Cognito the `UpdateUserPool` permission, deployment fails.

Add missing IAM policy

---

docs/SETUP.md

This fixes a Markdown error and a missing file suffix.

Fix inaccurate policy-generation command

---

docs/SETUP.md

The move to using AWS ECR requires retrieving the Docker container from there, and the URL includes the AWS account ID. So we must store that in CircleCI, and this documents that.

Specify need for AWS account ID in CircleCI

---

README.md

As of sprint 33, it is no longer necessary to maintain these forked dependencies. They have been deleted.

Remove explanation of forked dependencies

---

.github/PULL_REQUEST_TEMPLATE/merge-to-master.md

Including a Snyk badge means that it can be determined at a glance whether there are any dependencies that have known security holes.

Add Snyk badge to the merge-to-master template

---

docs/SETUP.md
docs/branch-management.md

This updates several aspects of the documentation around the deployment process:
- Adds a step missing from the deploy process
- Documents what happens after reviewing a vendor PR, to get it deployed
- Removes a redundant step from the setup process

Documentation updates around deployment process

---

iam/terraform/environment-specific/bin/deploy-app.sh

I keep running `deploy-app.sh` without the necessary variables set, and only discovering that via downstream errors. Instead, check that they exist before doing anything else.

Add sanity-checking to deploy-app script

---

docs/SETUP.md

This step was missing, and it meant that new environments are _tested,_ but not built.

Add CircleCI config to new environment instructions

---

docs/ENVIRONMENT_DESTRUCTION.md
docs/SETUP.md

* Remove a setup instruction left over from "Create a Route53 Hosted Zone," which was moved down further in the instructions.
* Specify the version of Terraform required.
* Make a series of edits to the environment destruction guide, made while actually stepping through the process for the first time.

Setup instruction improvements, edit environment destruction

---

docs/TROUBLESHOOTING.md

Provide instructions for what to do when receiving an error about the "limit for stack."
(We made this change to the documentation previously, but it caused a merge conflict, so here I am making it again.)

Re-add stack limit instructions

---

web-api/runtimes/clamav/Dockerfile

Cherry-picking from https://github.com/flexion/ef-cms/pull/5357 to fix the build issue — there were no strong preferences after speaking with Eric/Kelsey/Julia on how this is done. 
The dependency changed due to `yum` installing different package versions. Adding this to our list to look at when we review how to lock down deploy dependencies.
- [Related Slack thread](https://ustaxcourt.slack.com/archives/CD4PNKEPK/p1591032606006600), for the future.

Fix builds by adding newly-required dependencies.

---

web-api/terraform/bin/deploy-app.sh

Our deployment is currently failing due to reaching a size limit on a lambda function: https://app.circleci.com/pipelines/github/ustaxcourt/ef-cms/299/workflows/342dc4ea-5c58-4805-a164-5af9ec99cc1d/jobs/3139
Flexion ran into this issue too and resolved to remove the `--no-minify` flag to move past the issue - there may be work in the future to switch to deploying via S3 instead of direct upload. @ericsorenson

Remove no-minify flag from npx parcel command
